### ISSUE TITLE
Fastqc Docker

### ISSUE THREAD

**Issue by 223050025** [cuhk-haosun/code-docker-fastqc#2]
1. Add new function: 
If not find any fastq.gz, give an error message.
fastqc to use 4 threads.
fastqc and multiqc is install at Dockerfile.
The script name change to "run.sh".
2. Test in my own docker hub step by step: build-tag-push-pull-run.
3. The fastqc.yml is created.
4. The README.md is updated.

@Milokita

**Comment by Milokita** [comment]
The readme.md needs to a rework, the title should be "how to run" etc...
The location of the yml file isn't correct so that it can't be run by github

**Comment by 223050025** [comment]
The yml file is moved to **.github/workflows/fastqc.yml** path.
The **readme.md** is changed name as **How-to-run-docker-fastqc.md**.
