### ISSUE TITLE
Adjust to the entrypoint.sh

### ISSUE THREAD

**Issue by Milokita** [cuhk-haosun/code-docker-fastqc#4]
1. add env vars "INPUT_PATH" for setting input path
2. change default output path to "/mnt/out"

3. the current latest run command is faulty, you need to download the script in dockerfile
```
Status: Downloaded newer image for ghcr.io/cuhk-haosun/code-docker-fastqc:main
Info: Running set.thread.num.sh to set THREAD_NUM...
/entrypoint.sh: line 11: /root/set.thread.num.sh: No such file or directory

```

4. update the entrypoint.sh accordingly

**Comment by 223050025** [comment]
Updata accordingly.
